spring:
  profiles:
    active: local
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true 
      use_sql_comments: true
  datasource:
    sql-script-encoding: UTF-8   
---
spring:
  profiles: production
  datasource:
    platform: mariadb
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://withkid-rdb:3306/with-kid
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    host: withkid-redis
    port: 6379
  h2:
    console:
      enabled: true
logging:
  level:
    root: info
server:
  port: 8081
---
spring:
  profiles: local
  datasource:
    platform: mariadb
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.99.100:3306/with-kid
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    host: 192.168.99.100
    port: 6379
  h2:
    console:
      enabled: true
logging:
  level:
    root: info
server:
  port: 8081
---
spring:
  profiles: test
  jpa:
    hibernate: 
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true 
      use_sql_comments: true
  output: 
     ansi: 
      enabled: always
  redis:
    host: localhost
    port: 9000
#  datasource:
#    sql-script-encoding: UTF-8     
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:tcp://localhost/~/test
#    username: sa
#    password: 
logging:
  level:
    root: info
    com.crawling: debug